apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    tier: database
spec:
  ports:
  - protocol: TCP
    port: 27017 # Service Port
    targetPort: 27017 # container Port
  clusterIP: None
  selector:
    app: mongodb
    project: roboshop
    tier: database