apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    project: roboshop
    tier: database
spec:
  ports:
  - protocol: TCP
    port: 3306 # Service Port
    targetPort: 3306 # container Port
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: database