apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mysql
        image: "nanda1805/mysql:{{ .Values.statefulset.imageVersion }}"
        args:
        - "--ignore-db-dir=lost+found"
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql-secret
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 2Gi

