apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    project: roboshop
    tier: database
spec:
  ports:
  - protocol: TCP
    port: 6379 # Service Port
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    tier: database