apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: {{ .Values.statefulset.replicas}} # by default is 1
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        tier: database
    spec:
      containers:
      - name: redis
        image: "nanda1805/redis: {{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: www
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi

