apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
     app: cart
     project: roboshop
     tier: app
  template: #pod definition
    metadata:
      labels: #these labels are pods labels
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: nanda1805/cart:v1
        imagePullPolicy: Always #Always, IfNotPresent, Never it will pull the image from the docker hub
        envFrom:
        - configMapRef:
            name: cart