apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672 # Service Port
      targetPort: 5672 # container Port